dependencies:
  build:
   - maven:3.6.3
   - java:11.0.8
   
build_targets:
  - name: default
    container:
      image: yourbase/yb_ubuntu:18.04
    environment:
      - MVN_LOCAL_REPO_OPT='-Dmaven.repo.local=.repository'
      - MVN_TEST_FAIL_IGNORE='-Dmaven.test.failure.ignore=true'
    commands:
      - mvn -U -B -e clean install -DskipTests
      - mvn test
      - mvn -pl itests clean install -Pintegration-tests
ci:
  builds:
    - name: default
      build_target: default
